### ISSUE TITLE
support more Invidious instances?

### ISSUE THREAD

**Issue by atomGit** [2secslater/Invidify#1]
i use Invidious myself with Header Editor handling the redirects - the problem is that none of the instances are work all the time, therefor you might want to consider supporting [multiple instances](https://github.com/omarroth/invidious/wiki/Invidious-Instances) and perhaps testing connectivity and switching automatically (like to the first one that returns a ping if that's even possible?)

**Comment by 2secslater** [comment]
Sounds like an interesting idea, I'll definitely get to playing around and see what works.

**Comment by 2secslater** [comment]
Alrighty, in both the popup and add-on preferences, you can change the Invidious instance as you please. I have not added any functionality relating to pinging multiple instances and determining which one is faster as it will require more permissions, turning users off, and currently I do not have the knowledge of adding such features (sorry!).
